-- ============================================================================
-- Schema slice para el spike de liga-offline (Fase 0).
-- Extraído por introspección del Supabase en vivo de `lliga` (proyecto
-- jdbjgrkvwawdibntngpk) el 2026-07-07, no de los ficheros de migración
-- (que están repartidos en 93 ALTER incrementales). Se omiten a propósito
-- las FKs hacia tablas fuera del slice (leagues, continents, auth.users,
-- profiles, users, national_teams, referees) porque pertenecen a sistemas
-- excluidos (managers/auth) o aún no portados en esta fase — las columnas
-- se conservan para compatibilidad futura, solo se quita la constraint.
-- ============================================================================

CREATE TYPE competition_type_enum AS ENUM ('league', 'cup', 'mixed', 'ranked');

-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE seasons (
  id         bigint PRIMARY KEY,
  name       text NOT NULL UNIQUE,
  is_active  boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE clubs (
  id           bigint PRIMARY KEY,
  name         text NOT NULL,
  short_name   text,
  tla          text,
  crest_url    text,
  country      text,
  venue        text,
  created_at   timestamptz DEFAULT now(),
  address      text,
  website      text,
  founded      integer,
  club_colors  text,
  league_id    integer,   -- sin FK: `leagues` fuera del slice
  continent_id integer,   -- sin FK: `continents` fuera del slice
  pes_name     text,
  city         text
);

CREATE TABLE players (
  id                  bigint PRIMARY KEY,
  name                text NOT NULL,
  position            text,
  date_of_birth       date,
  nationality         text,
  created_at          timestamptz DEFAULT now(),
  efootball_id        integer,
  efootball_overall   smallint,
  efootball_potential smallint,
  efootball_cost_gp   integer
);

CREATE TABLE competitions (
  id                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                  text NOT NULL,
  slug                  text NOT NULL UNIQUE,
  description           text,
  season                text NOT NULL,
  is_official           boolean DEFAULT false,
  is_public             boolean DEFAULT false,
  status                text DEFAULT 'draft' CHECK (status = ANY (ARRAY['draft','open','active','finished'])),
  max_teams             integer NOT NULL DEFAULT 2 CHECK (max_teams >= 2 AND max_teams <= 32),
  min_teams             integer DEFAULT 2,
  registration_deadline date,
  start_date            date,
  end_date              date,
  created_by            uuid,   -- sin FK: auth.users fuera del slice (managers/auth excluido)
  created_at            timestamptz DEFAULT now(),
  updated_at            timestamptz DEFAULT now(),
  competition_type      competition_type_enum DEFAULT 'league',
  config                jsonb DEFAULT '{}'::jsonb,
  creator_id            uuid,   -- sin FK: profiles fuera del slice
  type_config           jsonb NOT NULL DEFAULT '{}'::jsonb,
  theme_preset          text DEFAULT 'default' CHECK (theme_preset = ANY (ARRAY['default','christmas','halloween'])),
  theme_colors          jsonb,
  logo_url              text,
  parent_competition_id integer REFERENCES competitions(id) ON DELETE SET NULL
);

CREATE TABLE rounds (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season         text NOT NULL,
  number         integer NOT NULL,
  name           text,
  competition_id integer REFERENCES competitions(id),
  UNIQUE (competition_id, season, number)
);

CREATE TABLE league_teams (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season            text NOT NULL,
  user_id           integer,   -- sin FK: `users` fuera del slice (managers/auth excluido)
  club_id           bigint REFERENCES clubs(id) ON DELETE SET NULL,
  nickname          text NOT NULL,
  display_name      text,
  created_at        timestamptz DEFAULT now(),
  penalty_points    integer NOT NULL DEFAULT 0,
  penalty_reason    text,
  updated_at        timestamptz DEFAULT now(),
  created_by        uuid,   -- sin FK: auth.users fuera del slice
  updated_by        uuid,   -- sin FK: auth.users fuera del slice
  competition_id    integer NOT NULL REFERENCES competitions(id),
  national_team_id  bigint,  -- sin FK: `national_teams` fuera del slice
  team_kind         text NOT NULL DEFAULT 'club' CHECK (team_kind = ANY (ARRAY['club','national'])),
  CONSTRAINT league_teams_kind_xor CHECK (
    (team_kind = 'club' AND club_id IS NOT NULL AND national_team_id IS NULL) OR
    (team_kind = 'national' AND national_team_id IS NOT NULL AND club_id IS NULL)
  )
);

CREATE TABLE matches (
  id                        text NOT NULL,
  season                    text NOT NULL,
  -- SIN FK real a rounds(id) a propósito: competition-schedule-generator.js
  -- (generateLeagueSchedule, camino round-robin estándar, sin modificar)
  -- escribe aquí el número de jornada directamente vía INSERT sin crear
  -- filas en `rounds` — con la FK puesta, ese INSERT falla siempre (rounds
  -- vacía). Coincide con lo descrito en la memoria jornada-round-id-vs-number
  -- ("coincidían por azar en comp 1"). Consecuencia aceptada: las páginas que
  -- hacen embed `round:rounds!matches_round_id_fkey(...)` (p.ej. algún
  -- widget de próximo/último partido) reciben 400 de PostgREST porque no
  -- hay relación de FK que resolver — ya degradan con try/catch, igual que
  -- el hueco conocido de team_fanbase_state.
  round_id                  integer,
  home_league_team_id       integer REFERENCES league_teams(id) ON DELETE SET NULL,
  away_league_team_id       integer REFERENCES league_teams(id) ON DELETE SET NULL,
  match_date                date,
  match_time                time,
  home_goals                integer CHECK (home_goals IS NULL OR home_goals >= 0),
  away_goals                integer CHECK (away_goals IS NULL OR away_goals >= 0),
  stream_url                text,
  created_at                timestamptz DEFAULT now(),
  updated_at                timestamptz DEFAULT now(),
  created_by                uuid,  -- sin FK: auth.users fuera del slice
  updated_by                uuid,  -- sin FK: auth.users fuera del slice
  is_played                 boolean,
  competition_id            integer REFERENCES competitions(id),
  round_type                varchar(20) DEFAULT 'league',
  group_name                varchar(50),
  cup_round                 integer,
  cup_leg                   varchar(20),
  is_cup_final              boolean DEFAULT false,
  match_uuid                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  is_third_place_match      boolean NOT NULL DEFAULT false,
  has_penalties             boolean DEFAULT false,
  penalties_winner_id       integer REFERENCES league_teams(id),
  bracket_type              text CHECK (bracket_type = ANY (ARRAY['winner','loser'])),
  resolved_administratively boolean DEFAULT false,
  highlights_url            text,
  referee_id                bigint,  -- sin FK: `referees` fuera del slice (se porta en Fase 1)
  UNIQUE (competition_id, id)
);

CREATE TABLE match_team_stats (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id         text,
  league_team_id   integer REFERENCES league_teams(id) ON DELETE SET NULL,
  possession       integer,
  shots            integer,
  shots_on_target  integer,
  goals            integer,
  fouls            integer,
  offsides         integer,
  corners          integer,
  free_kicks       integer,
  passes           integer,
  passes_completed integer,
  crosses          integer,
  interceptions    integer,
  tackles          integer,
  saves            integer,
  red_cards        integer,
  created_at       timestamptz DEFAULT now(),
  competition_id   integer REFERENCES competitions(id),
  season           text,
  match_uuid       integer NOT NULL REFERENCES matches(match_uuid) ON DELETE CASCADE,
  UNIQUE (match_id, league_team_id)
);

CREATE TABLE match_player_ratings (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id       varchar(50),
  match_uuid     integer NOT NULL REFERENCES matches(match_uuid) ON DELETE CASCADE,
  league_team_id integer NOT NULL REFERENCES league_teams(id) ON DELETE CASCADE,
  competition_id integer NOT NULL REFERENCES competitions(id) ON DELETE CASCADE,
  season         varchar(20) NOT NULL,
  player_id      integer REFERENCES players(id) ON DELETE CASCADE,
  player_name    varchar(255) NOT NULL,
  rating         numeric,
  created_at     timestamptz DEFAULT now(),
  is_synthetic   boolean NOT NULL DEFAULT false,
  is_starter     boolean,
  lineup_order   smallint,
  UNIQUE (match_uuid, league_team_id, player_name)
);

CREATE TABLE player_club_memberships (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id  bigint REFERENCES players(id) ON DELETE CASCADE,
  club_id    bigint REFERENCES clubs(id) ON DELETE CASCADE,
  season     text NOT NULL,
  from_round integer,
  to_round   integer,
  is_current boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  UNIQUE (player_id, club_id, season)
);

CREATE TABLE goal_events (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id        text,
  league_team_id  integer REFERENCES league_teams(id) ON DELETE SET NULL,
  player_id       bigint REFERENCES players(id) ON DELETE SET NULL,
  minute          integer,
  event_type      text DEFAULT 'goal',
  created_at      timestamptz DEFAULT now(),
  competition_id  integer REFERENCES competitions(id),
  season          text,
  match_uuid      integer NOT NULL REFERENCES matches(match_uuid) ON DELETE CASCADE,
  vod_offset_seconds integer,
  clip_url        text
);

CREATE TABLE match_red_cards (
  -- id sin default en producción (el OCR/lambda lo asigna); aquí necesita
  -- IDENTITY porque simulate-match.js no genera un id explícito.
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id        text NOT NULL,
  league_team_id  bigint NOT NULL REFERENCES league_teams(id),
  player_id       bigint NOT NULL REFERENCES players(id),
  created_at      timestamptz DEFAULT now(),
  competition_id  integer REFERENCES competitions(id),
  season          text,
  match_uuid      integer NOT NULL REFERENCES matches(match_uuid) ON DELETE CASCADE,
  vod_offset_seconds integer,
  minute          integer
);

CREATE TABLE mvp_jornada (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  league_team_id integer NOT NULL REFERENCES league_teams(id) ON DELETE CASCADE,
  competition_id integer NOT NULL REFERENCES competitions(id) ON DELETE CASCADE,
  season         text NOT NULL,
  jornada        integer NOT NULL,
  mvp_score      numeric NOT NULL,
  created_at     timestamptz DEFAULT now(),
  updated_at     timestamptz DEFAULT now(),
  UNIQUE (league_team_id, competition_id, season, jornada)
);

CREATE TABLE player_morale_state (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id     bigint NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  season        text NOT NULL,
  score         integer NOT NULL DEFAULT 50 CHECK (score >= 0 AND score <= 100),
  last_event_at timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (player_id, season)
);

-- ─────────────────────────────────────────────────────────────────────
-- Vista y funciones reales, copiadas tal cual del proyecto en vivo
-- (pg_get_viewdef / pg_get_functiondef) para probar que plpgsql/vistas
-- funcionan igual en PGlite.
-- ─────────────────────────────────────────────────────────────────────

CREATE VIEW league_standings AS
WITH team_matches AS (
  SELECT m.home_league_team_id AS league_team_id,
         m.competition_id,
         c.season,
         m.round_id,
         m.id AS match_id,
         m.home_goals AS goals_for,
         m.away_goals AS goals_against,
         CASE
           WHEN m.home_goals > m.away_goals THEN 1
           WHEN m.home_goals = m.away_goals THEN 0
           ELSE -1
         END AS result,
         COALESCE((c.type_config ->> 'points_win')::integer, 3) AS points_win,
         COALESCE((c.type_config ->> 'points_draw')::integer, 1) AS points_draw,
         COALESCE((c.type_config ->> 'points_loss')::integer, 0) AS points_loss
  FROM matches m
  JOIN competitions c ON m.competition_id = c.id
  WHERE c.competition_type = 'league'::competition_type_enum
    AND m.home_goals IS NOT NULL AND m.away_goals IS NOT NULL
    AND (m.round_type IS NULL OR m.round_type::text = 'league')
    AND m.home_league_team_id IS NOT NULL
  UNION ALL
  SELECT m.away_league_team_id AS league_team_id,
         m.competition_id,
         c.season,
         m.round_id,
         m.id AS match_id,
         m.away_goals AS goals_for,
         m.home_goals AS goals_against,
         CASE
           WHEN m.away_goals > m.home_goals THEN 1
           WHEN m.away_goals = m.home_goals THEN 0
           ELSE -1
         END AS result,
         COALESCE((c.type_config ->> 'points_win')::integer, 3) AS points_win,
         COALESCE((c.type_config ->> 'points_draw')::integer, 1) AS points_draw,
         COALESCE((c.type_config ->> 'points_loss')::integer, 0) AS points_loss
  FROM matches m
  JOIN competitions c ON m.competition_id = c.id
  WHERE c.competition_type = 'league'::competition_type_enum
    AND m.home_goals IS NOT NULL AND m.away_goals IS NOT NULL
    AND (m.round_type IS NULL OR m.round_type::text = 'league')
    AND m.away_league_team_id IS NOT NULL
)
SELECT tm.league_team_id,
       tm.competition_id,
       tm.season,
       max(tm.round_id) AS jornada_max,
       count(DISTINCT tm.match_id) AS pj,
       sum(CASE WHEN tm.result = 1 THEN 1 ELSE 0 END) AS g,
       sum(CASE WHEN tm.result = 0 THEN 1 ELSE 0 END) AS e,
       sum(CASE WHEN tm.result = -1 THEN 1 ELSE 0 END) AS p,
       sum(COALESCE(tm.goals_for, 0)) AS gf,
       sum(COALESCE(tm.goals_against, 0)) AS gc,
       sum(COALESCE(tm.goals_for, 0)) - sum(COALESCE(tm.goals_against, 0)) AS goal_difference,
       sum(CASE WHEN tm.result = 1 THEN tm.points_win WHEN tm.result = 0 THEN tm.points_draw ELSE tm.points_loss END) AS pts_raw,
       COALESCE(lt.penalty_points, 0) AS penalty_points,
       GREATEST(
         sum(CASE WHEN tm.result = 1 THEN tm.points_win WHEN tm.result = 0 THEN tm.points_draw ELSE tm.points_loss END)
         - COALESCE(lt.penalty_points, 0), 0
       ) AS pts
FROM team_matches tm
LEFT JOIN league_teams lt ON tm.league_team_id = lt.id
GROUP BY tm.league_team_id, tm.competition_id, tm.season, lt.penalty_points;

CREATE OR REPLACE FUNCTION calculate_mvp_jornada(p_competition_id integer, p_jornada integer)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_season TEXT;
    c_conv   CONSTANT numeric := 0.253;
    s_conv   CONSTANT numeric := 0.111;
    mu_sot   CONSTANT numeric := 4.38;
    s_sot    CONSTANT numeric := 2.76;
    mu_pos   CONSTANT numeric := 50.0;
    s_pos    CONSTANT numeric := 5.3;
    mu_pass  CONSTANT numeric := 0.761;
    s_pass   CONSTANT numeric := 0.063;
    mu_fpr   CONSTANT numeric := 4.02;
    s_fpr    CONSTANT numeric := 2.90;
    s_gd     CONSTANT numeric := 2.58;
    a_shr    CONSTANT numeric := 4.0;
BEGIN
    SELECT season INTO v_season FROM competitions WHERE id = p_competition_id;
    IF v_season IS NULL THEN
        RAISE EXCEPTION 'No se encontró la competición %', p_competition_id;
    END IF;

    WITH jornada_matches AS (
        SELECT m.match_uuid, m.home_league_team_id, m.away_league_team_id, m.home_goals, m.away_goals
        FROM matches m
        WHERE m.competition_id = p_competition_id
          AND m.round_id = p_jornada
          AND (m.resolved_administratively IS NULL OR m.resolved_administratively = false)
          AND m.home_goals IS NOT NULL
          AND m.away_goals IS NOT NULL
    ),
    team_match_stats AS (
        SELECT
            mts.league_team_id,
            m.match_uuid,
            mts.possession, mts.passes, mts.passes_completed,
            mts.shots, mts.shots_on_target, mts.tackles, mts.fouls, mts.red_cards,
            CASE WHEN m.home_league_team_id = mts.league_team_id THEN m.home_goals ELSE m.away_goals END AS team_goals,
            CASE WHEN m.home_league_team_id = mts.league_team_id THEN m.away_goals ELSE m.home_goals END AS goals_conceded,
            rival.shots AS rival_shots,
            rival.shots_on_target AS rival_sot
        FROM jornada_matches m
        INNER JOIN match_team_stats mts ON mts.match_uuid = m.match_uuid
        LEFT JOIN match_team_stats rival ON
            rival.match_uuid = m.match_uuid AND rival.league_team_id <> mts.league_team_id
        WHERE (mts.possession IS NOT NULL OR mts.fouls IS NOT NULL OR mts.tackles IS NOT NULL
            OR mts.passes IS NOT NULL OR mts.shots IS NOT NULL)
    ),
    team_aggregated AS (
        SELECT
            league_team_id,
            COUNT(DISTINCT match_uuid) AS pj,
            SUM(COALESCE(team_goals, 0)) AS gf,
            SUM(COALESCE(goals_conceded, 0)) AS gc,
            SUM(COALESCE(shots, 0)) AS shots,
            SUM(COALESCE(shots_on_target, 0)) AS sot,
            SUM(COALESCE(rival_shots, 0)) AS rival_shots,
            SUM(COALESCE(rival_sot, 0)) AS rival_sot,
            SUM(COALESCE(passes, 0)) AS passes,
            SUM(COALESCE(passes_completed, 0)) AS passes_completed,
            SUM(COALESCE(tackles, 0)) AS tackles,
            SUM(COALESCE(fouls, 0)) AS fouls,
            SUM(COALESCE(red_cards, 0)) AS red_cards,
            AVG(possession::numeric) AS avg_possession
        FROM team_match_stats
        WHERE league_team_id IS NOT NULL
        GROUP BY league_team_id
        HAVING COUNT(DISTINCT match_uuid) > 0
    ),
    team_quality AS (
        SELECT
            league_team_id,
            (gf + a_shr * c_conv) / (shots + a_shr)                 AS fin_rate,
            (gc + a_shr * c_conv) / (rival_shots + a_shr)           AS def_rate,
            sot::numeric / pj                                       AS sot_pm,
            rival_sot::numeric / pj                                 AS rsot_pm,
            COALESCE(avg_possession, mu_pos)                        AS pos_pm,
            CASE WHEN passes > 0 THEN passes_completed::numeric / passes ELSE mu_pass END AS passacc,
            (tackles + 1)::numeric / (fouls + 5 * red_cards + 1)    AS fpr,
            (gf - gc)::numeric / pj                                 AS gd_pm
        FROM team_aggregated
    ),
    team_scores AS (
        SELECT
            league_team_id,
            (
                0.22 * (1.0 / (1 + exp(-((fin_rate - c_conv) / s_conv)))) +
                0.22 * (1.0 / (1 + exp(-((c_conv - def_rate) / s_conv)))) +
                0.11 * (1.0 / (1 + exp(-((sot_pm - mu_sot) / s_sot)))) +
                0.11 * (1.0 / (1 + exp(-((mu_sot - rsot_pm) / s_sot)))) +
                0.07 * (1.0 / (1 + exp(-((pos_pm - mu_pos) / s_pos)))) +
                0.07 * (1.0 / (1 + exp(-((passacc - mu_pass) / s_pass)))) +
                0.08 * (1.0 / (1 + exp(-((fpr - mu_fpr) / s_fpr)))) +
                0.12 * (1.0 / (1 + exp(-((gd_pm) / s_gd))))
            ) AS mvp_score
        FROM team_quality
    )
    INSERT INTO mvp_jornada (league_team_id, competition_id, season, jornada, mvp_score)
    SELECT league_team_id, p_competition_id, v_season, p_jornada, mvp_score
    FROM team_scores
    ON CONFLICT (league_team_id, competition_id, season, jornada)
    DO UPDATE SET mvp_score = EXCLUDED.mvp_score, updated_at = NOW();
END;
$function$;

CREATE OR REPLACE FUNCTION _player_morale_apply_decay()
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_season text;
  v_count  integer := 0;
BEGIN
  SELECT name INTO v_season FROM public.seasons WHERE is_active = true LIMIT 1;
  IF v_season IS NULL THEN RETURN 0; END IF;

  WITH updated AS (
    UPDATE public.player_morale_state
    SET score = GREATEST(0, LEAST(100,
              score + (sign(50 - score)::int) * GREATEST(1, round(abs(50 - score) * 0.05)::int)
            )),
        last_event_at = now()
    WHERE season = v_season
      AND score <> 50
    RETURNING 1
  )
  SELECT COUNT(*)::int INTO v_count FROM updated;

  RETURN v_count;
END;
$function$;
