-- ============================================================================
-- Geografía/referencia: continents, leagues, national_teams, team_cities,
-- player_national_team_memberships. Introspectado del Supabase en vivo
-- 2026-07-07. Añade también las FKs de clubs/league_teams hacia estas tablas
-- que en el slice de la Fase 0 se omitieron por no existir aún el destino.
-- ============================================================================

CREATE TABLE continents (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code       varchar NOT NULL UNIQUE,
  name       varchar NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE leagues (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         varchar NOT NULL,
  country      varchar NOT NULL,
  continent_id integer REFERENCES continents(id),
  short_name   varchar,
  created_at   timestamptz DEFAULT now()
);

CREATE TABLE national_teams (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text NOT NULL,
  short_name    text,
  tla           text UNIQUE,
  crest_url     text,
  confederation text,
  external_id   integer,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE player_national_team_memberships (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id        bigint REFERENCES players(id) ON DELETE CASCADE,
  national_team_id bigint REFERENCES national_teams(id) ON DELETE CASCADE,
  season           text NOT NULL,
  from_round       integer,
  to_round         integer,
  is_current       boolean DEFAULT false,
  created_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (player_id, national_team_id, season)
);

CREATE TABLE team_cities (
  id         bigint PRIMARY KEY,
  nickname   text NOT NULL UNIQUE,
  city       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Completar FKs que en 01 (spike.sql) se omitieron por no existir aún el destino.
ALTER TABLE clubs ADD CONSTRAINT clubs_league_id_fkey FOREIGN KEY (league_id) REFERENCES leagues(id);
ALTER TABLE clubs ADD CONSTRAINT clubs_continent_id_fkey FOREIGN KEY (continent_id) REFERENCES continents(id);
ALTER TABLE league_teams ADD CONSTRAINT league_teams_national_team_id_fkey FOREIGN KEY (national_team_id) REFERENCES national_teams(id) ON DELETE SET NULL;
