-- Árbitros (introspectado 2026-07-07). Independiente del sistema de fanbase
-- (que queda fuera de este pase); solo la tabla base + la FK de matches.
CREATE TABLE referees (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name text NOT NULL,
  last_name  text NOT NULL,
  gender     text NOT NULL CHECK (gender = ANY (ARRAY['M','F','X'])),
  birth_year integer NOT NULL CHECK (birth_year >= 1950 AND birth_year <= 2020),
  ethnicity  text NOT NULL,
  tier       text NOT NULL CHECK (tier = ANY (ARRAY['voll','estrella'])),
  nickname   text,
  archetype  text,
  lore_short text,
  lore_long  text,
  photo_url  text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE matches ADD CONSTRAINT matches_referee_id_fkey FOREIGN KEY (referee_id) REFERENCES referees(id) ON DELETE SET NULL;
