-- Tarjetas amarillas, lesiones y sanciones (introspectado 2026-07-07).

-- Sustituciones del partido (añadido 2026-07-10 para la simulación por tramos).
CREATE TABLE IF NOT EXISTS match_substitutions (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id       text NOT NULL,
  match_uuid     integer NOT NULL REFERENCES matches(match_uuid) ON DELETE CASCADE,
  league_team_id integer NOT NULL REFERENCES league_teams(id),
  player_off_id  bigint REFERENCES players(id),
  player_on_id   bigint REFERENCES players(id),
  minute         integer,
  competition_id integer REFERENCES competitions(id),
  season         text,
  created_at     timestamptz DEFAULT now()
);

CREATE TABLE match_yellow_cards (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id           text NOT NULL,
  match_uuid         integer NOT NULL REFERENCES matches(match_uuid),
  league_team_id     integer NOT NULL REFERENCES league_teams(id),
  player_id          bigint REFERENCES players(id),
  minute             integer,
  competition_id     integer REFERENCES competitions(id),
  season             text,
  created_at         timestamptz DEFAULT now(),
  vod_offset_seconds integer
);

CREATE TABLE match_injuries (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id       text NOT NULL,
  league_team_id bigint NOT NULL REFERENCES league_teams(id) ON DELETE CASCADE,
  player_id      bigint NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  created_at     timestamptz DEFAULT now(),
  competition_id integer REFERENCES competitions(id),
  season         text,
  match_uuid     integer NOT NULL REFERENCES matches(match_uuid) ON DELETE CASCADE,
  matches_out    integer DEFAULT 1,  -- partidos de baja (1-4); añadido 2026-07-10
  origin_round   integer,            -- round_id del partido donde se lesionó
  minute         integer,            -- minuto de la lesión
  UNIQUE (match_id, player_id)
);

CREATE TABLE player_suspensions (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id         bigint NOT NULL REFERENCES players(id),
  league_team_id    bigint NOT NULL REFERENCES league_teams(id),
  match_id          text NOT NULL,
  origin_match_id   text NOT NULL,
  reason            text DEFAULT 'red_card',
  created_at        timestamptz DEFAULT now(),
  competition_id    integer REFERENCES competitions(id),
  season            text,
  match_uuid        integer REFERENCES matches(match_uuid) ON DELETE SET NULL,
  origin_match_uuid integer REFERENCES matches(match_uuid) ON DELETE SET NULL,
  UNIQUE (player_id, match_id)
);
