-- Best XI / mejor jugador de jornada / premios del mes / MVP temporada.
-- Introspectado 2026-07-07. Todo esto se recalcula automáticamente vía
-- triggers cuando entran ratings/resultados, igual que en producción.

CREATE OR REPLACE FUNCTION classify_position(pos text)
 RETURNS character varying
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
DECLARE
    pos_lower TEXT;
BEGIN
    IF pos IS NULL THEN RETURN NULL; END IF;
    pos_lower := LOWER(pos);
    IF pos_lower LIKE '%goalkeeper%' OR pos_lower LIKE '%portero%' THEN RETURN 'GK'; END IF;
    IF pos_lower LIKE '%defence%' OR pos_lower LIKE '%back%' OR pos_lower LIKE '%centre-back%' OR pos_lower LIKE '%defensa%' THEN RETURN 'DEF'; END IF;
    IF pos_lower LIKE '%midfield%' OR pos_lower LIKE '%medio%' OR pos_lower LIKE '%mid%' THEN RETURN 'MID'; END IF;
    IF pos_lower LIKE '%offence%' OR pos_lower LIKE '%forward%' OR pos_lower LIKE '%wing%' OR pos_lower LIKE '%striker%' OR pos_lower LIKE '%delantero%' THEN RETURN 'FWD'; END IF;
    RETURN NULL;
END;
$function$;

CREATE TABLE best_player_jornada (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  competition_id integer NOT NULL REFERENCES competitions(id) ON DELETE CASCADE,
  season         text NOT NULL,
  jornada        integer NOT NULL,
  player_id      integer REFERENCES players(id) ON DELETE SET NULL,
  league_team_id bigint REFERENCES league_teams(id) ON DELETE SET NULL,
  avg_rating     numeric,
  goals          integer DEFAULT 0,
  created_at     timestamptz DEFAULT now(),
  updated_at     timestamptz DEFAULT now(),
  UNIQUE (competition_id, season, jornada)
);

CREATE TABLE best_xi_jornada (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  competition_id integer NOT NULL REFERENCES competitions(id) ON DELETE CASCADE,
  season         text NOT NULL,
  jornada        integer NOT NULL,
  player_id      integer NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  position       varchar NOT NULL,
  position_order integer NOT NULL,
  avg_rating     numeric NOT NULL,
  matches_count  integer NOT NULL DEFAULT 1,
  created_at     timestamptz DEFAULT now(),
  updated_at     timestamptz DEFAULT now(),
  UNIQUE (competition_id, season, jornada, player_id)
);

CREATE TABLE competition_best_eleven (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  palmares_id    integer NOT NULL REFERENCES competition_palmares(id) ON DELETE CASCADE,
  player_id      integer NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  position       varchar NOT NULL CHECK (position = ANY (ARRAY['GK','DEF','MID','FWD'])),
  position_order integer NOT NULL,
  UNIQUE (palmares_id, player_id)
);

CREATE TABLE monthly_awards (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  competition_id        integer NOT NULL REFERENCES competitions(id) ON DELETE CASCADE,
  season                text NOT NULL,
  period_number         integer NOT NULL,
  start_jornada         integer NOT NULL,
  end_jornada           integer NOT NULL,
  player_id             integer REFERENCES players(id) ON DELETE SET NULL,
  player_avg_rating     numeric,
  player_matches_count  integer,
  coach_league_team_id  integer REFERENCES league_teams(id) ON DELETE SET NULL,
  coach_avg_mvp_score   numeric,
  is_period_complete    boolean DEFAULT false,
  created_at            timestamptz DEFAULT now(),
  updated_at            timestamptz DEFAULT now(),
  UNIQUE (competition_id, season, period_number)
);

CREATE OR REPLACE FUNCTION update_best_xi_jornada_updated_at() RETURNS trigger LANGUAGE plpgsql AS $function$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$function$;
CREATE OR REPLACE FUNCTION update_monthly_awards_updated_at() RETURNS trigger LANGUAGE plpgsql AS $function$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$function$;
CREATE OR REPLACE FUNCTION update_mvp_jornada_updated_at() RETURNS trigger LANGUAGE plpgsql AS $function$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$function$;

CREATE TRIGGER trigger_update_best_xi_jornada_updated_at BEFORE UPDATE ON best_xi_jornada FOR EACH ROW EXECUTE FUNCTION update_best_xi_jornada_updated_at();
CREATE TRIGGER trigger_monthly_awards_updated_at BEFORE UPDATE ON monthly_awards FOR EACH ROW EXECUTE FUNCTION update_monthly_awards_updated_at();
CREATE TRIGGER trigger_update_mvp_jornada_updated_at BEFORE UPDATE ON mvp_jornada FOR EACH ROW EXECUTE FUNCTION update_mvp_jornada_updated_at();

CREATE OR REPLACE FUNCTION calculate_best_player_jornada(p_competition_id integer, p_season text, p_jornada integer)
 RETURNS void LANGUAGE plpgsql AS $function$
DECLARE
    v_best RECORD;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM matches
        WHERE competition_id = p_competition_id AND round_id = p_jornada
          AND home_goals IS NOT NULL AND away_goals IS NOT NULL
          AND (resolved_administratively IS NULL OR resolved_administratively = false)
    ) THEN
        DELETE FROM best_player_jornada WHERE competition_id = p_competition_id AND season = p_season AND jornada = p_jornada;
        RETURN;
    END IF;

    SELECT INTO v_best
        prj.player_id, prj.avg_rating,
        (SELECT mpr.league_team_id FROM match_player_ratings mpr
         INNER JOIN matches m ON m.match_uuid = mpr.match_uuid
         WHERE mpr.player_id = prj.player_id AND m.competition_id = p_competition_id
           AND m.season = p_season AND m.round_id = p_jornada LIMIT 1) AS league_team_id,
        COALESCE(goal_counts.goals, 0) AS goals
    FROM player_ratings_jornada prj
    LEFT JOIN LATERAL (
        SELECT COUNT(*)::INTEGER AS goals FROM goal_events ge
        INNER JOIN matches m ON ge.match_uuid = m.match_uuid
        WHERE ge.player_id = prj.player_id AND ge.event_type = 'goal'
          AND m.competition_id = p_competition_id AND m.season = p_season AND m.round_id = p_jornada
    ) goal_counts ON true
    WHERE prj.competition_id = p_competition_id AND prj.season = p_season AND prj.jornada = p_jornada
    ORDER BY prj.avg_rating DESC NULLS LAST, goal_counts.goals DESC, prj.player_id ASC
    LIMIT 1;

    IF v_best.player_id IS NULL THEN
        DELETE FROM best_player_jornada WHERE competition_id = p_competition_id AND season = p_season AND jornada = p_jornada;
        RETURN;
    END IF;

    INSERT INTO best_player_jornada (competition_id, season, jornada, player_id, league_team_id, avg_rating, goals, updated_at)
    VALUES (p_competition_id, p_season, p_jornada, v_best.player_id, v_best.league_team_id, v_best.avg_rating, v_best.goals, NOW())
    ON CONFLICT (competition_id, season, jornada)
    DO UPDATE SET player_id = EXCLUDED.player_id, league_team_id = EXCLUDED.league_team_id,
                  avg_rating = EXCLUDED.avg_rating, goals = EXCLUDED.goals, updated_at = NOW();
END;
$function$;

CREATE OR REPLACE FUNCTION calculate_best_xi_jornada(p_competition_id integer, p_season text, p_jornada integer)
 RETURNS void LANGUAGE plpgsql AS $function$
DECLARE
    v_gk RECORD; v_def RECORD; v_mid RECORD; v_fwd RECORD; v_best_player RECORD;
    v_pos_classified VARCHAR(10);
    def_order INTEGER := 0; mid_order INTEGER := 0; fwd_order INTEGER := 0;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM matches
        WHERE competition_id = p_competition_id AND round_id = p_jornada
          AND home_goals IS NOT NULL AND away_goals IS NOT NULL
          AND (resolved_administratively IS NULL OR resolved_administratively = false)
    ) THEN RETURN; END IF;

    DELETE FROM best_xi_jornada WHERE competition_id = p_competition_id AND season = p_season AND jornada = p_jornada;

    SELECT INTO v_best_player prj.*, COALESCE(goal_counts.goals, 0) as goals
    FROM player_ratings_jornada prj
    LEFT JOIN LATERAL (
        SELECT COUNT(*)::INTEGER as goals FROM goal_events ge
        INNER JOIN matches m ON ge.match_uuid = m.match_uuid
        WHERE ge.player_id = prj.player_id AND ge.event_type != 'own_goal'
          AND m.competition_id = p_competition_id AND m.season = p_season AND m.round_id = p_jornada
    ) goal_counts ON true
    WHERE prj.competition_id = p_competition_id AND prj.season = p_season AND prj.jornada = p_jornada
      AND classify_position(prj.position) IS NOT NULL
    ORDER BY prj.avg_rating DESC, goal_counts.goals DESC, prj.player_id ASC
    LIMIT 1;

    IF v_best_player IS NOT NULL THEN v_pos_classified := classify_position(v_best_player.position); END IF;

    SELECT INTO v_gk prj.*, COALESCE(goal_counts.goals, 0) as goals
    FROM player_ratings_jornada prj
    LEFT JOIN LATERAL (
        SELECT COUNT(*)::INTEGER as goals FROM goal_events ge
        INNER JOIN matches m ON ge.match_uuid = m.match_uuid
        WHERE ge.player_id = prj.player_id AND ge.event_type != 'own_goal'
          AND m.competition_id = p_competition_id AND m.season = p_season AND m.round_id = p_jornada
    ) goal_counts ON true
    WHERE prj.competition_id = p_competition_id AND prj.season = p_season AND prj.jornada = p_jornada
      AND classify_position(prj.position) = 'GK'
    ORDER BY prj.avg_rating DESC, goal_counts.goals DESC, prj.player_id ASC LIMIT 1;

    IF v_gk IS NOT NULL THEN
        INSERT INTO best_xi_jornada (competition_id, season, jornada, player_id, position, position_order, avg_rating, matches_count)
        VALUES (p_competition_id, p_season, p_jornada, v_gk.player_id, 'GK', 1, v_gk.avg_rating, v_gk.matches_count);
    END IF;

    def_order := 0;
    FOR v_def IN
        SELECT prj.*, COALESCE(goal_counts.goals, 0) as goals
        FROM player_ratings_jornada prj
        LEFT JOIN LATERAL (
            SELECT COUNT(*)::INTEGER as goals FROM goal_events ge
            INNER JOIN matches m ON ge.match_uuid = m.match_uuid
            WHERE ge.player_id = prj.player_id AND ge.event_type != 'own_goal'
              AND m.competition_id = p_competition_id AND m.season = p_season AND m.round_id = p_jornada
        ) goal_counts ON true
        WHERE prj.competition_id = p_competition_id AND prj.season = p_season AND prj.jornada = p_jornada
          AND classify_position(prj.position) = 'DEF'
        ORDER BY prj.avg_rating DESC, goal_counts.goals DESC, prj.player_id ASC LIMIT 4
    LOOP
        def_order := def_order + 1;
        INSERT INTO best_xi_jornada (competition_id, season, jornada, player_id, position, position_order, avg_rating, matches_count)
        VALUES (p_competition_id, p_season, p_jornada, v_def.player_id, 'DEF', def_order, v_def.avg_rating, v_def.matches_count);
    END LOOP;

    mid_order := 0;
    FOR v_mid IN
        SELECT prj.*, COALESCE(goal_counts.goals, 0) as goals
        FROM player_ratings_jornada prj
        LEFT JOIN LATERAL (
            SELECT COUNT(*)::INTEGER as goals FROM goal_events ge
            INNER JOIN matches m ON ge.match_uuid = m.match_uuid
            WHERE ge.player_id = prj.player_id AND ge.event_type != 'own_goal'
              AND m.competition_id = p_competition_id AND m.season = p_season AND m.round_id = p_jornada
        ) goal_counts ON true
        WHERE prj.competition_id = p_competition_id AND prj.season = p_season AND prj.jornada = p_jornada
          AND classify_position(prj.position) = 'MID'
        ORDER BY prj.avg_rating DESC, goal_counts.goals DESC, prj.player_id ASC LIMIT 3
    LOOP
        mid_order := mid_order + 1;
        INSERT INTO best_xi_jornada (competition_id, season, jornada, player_id, position, position_order, avg_rating, matches_count)
        VALUES (p_competition_id, p_season, p_jornada, v_mid.player_id, 'MID', mid_order, v_mid.avg_rating, v_mid.matches_count);
    END LOOP;

    fwd_order := 0;
    FOR v_fwd IN
        SELECT prj.*, COALESCE(goal_counts.goals, 0) as goals
        FROM player_ratings_jornada prj
        LEFT JOIN LATERAL (
            SELECT COUNT(*)::INTEGER as goals FROM goal_events ge
            INNER JOIN matches m ON ge.match_uuid = m.match_uuid
            WHERE ge.player_id = prj.player_id AND ge.event_type != 'own_goal'
              AND m.competition_id = p_competition_id AND m.season = p_season AND m.round_id = p_jornada
        ) goal_counts ON true
        WHERE prj.competition_id = p_competition_id AND prj.season = p_season AND prj.jornada = p_jornada
          AND classify_position(prj.position) = 'FWD'
        ORDER BY prj.avg_rating DESC, goal_counts.goals DESC, prj.player_id ASC LIMIT 3
    LOOP
        fwd_order := fwd_order + 1;
        INSERT INTO best_xi_jornada (competition_id, season, jornada, player_id, position, position_order, avg_rating, matches_count)
        VALUES (p_competition_id, p_season, p_jornada, v_fwd.player_id, 'FWD', fwd_order, v_fwd.avg_rating, v_fwd.matches_count);
    END LOOP;

    IF v_best_player IS NOT NULL AND v_pos_classified IS NOT NULL THEN
        IF v_best_player.player_id NOT IN (
            SELECT player_id FROM best_xi_jornada
            WHERE competition_id = p_competition_id AND season = p_season AND jornada = p_jornada
        ) THEN
            DELETE FROM best_xi_jornada
            WHERE competition_id = p_competition_id AND season = p_season AND jornada = p_jornada
              AND position = v_pos_classified
              AND player_id = (
                  SELECT bxi.player_id FROM best_xi_jornada bxi
                  LEFT JOIN LATERAL (
                      SELECT COUNT(*)::INTEGER as goals FROM goal_events ge
                      INNER JOIN matches m ON ge.match_uuid = m.match_uuid
                      WHERE ge.player_id = bxi.player_id AND ge.event_type != 'own_goal'
                        AND m.competition_id = p_competition_id AND m.season = p_season AND m.round_id = p_jornada
                  ) goal_counts ON true
                  WHERE bxi.competition_id = p_competition_id AND bxi.season = p_season AND bxi.jornada = p_jornada
                    AND bxi.position = v_pos_classified
                  ORDER BY bxi.avg_rating ASC, goal_counts.goals ASC, bxi.position_order DESC LIMIT 1
              );

            INSERT INTO best_xi_jornada (competition_id, season, jornada, player_id, position, position_order, avg_rating, matches_count)
            VALUES (p_competition_id, p_season, p_jornada, v_best_player.player_id, v_pos_classified, 1, v_best_player.avg_rating, v_best_player.matches_count);

            UPDATE best_xi_jornada SET position_order = sub.new_order
            FROM (
                SELECT bxi.player_id,
                       ROW_NUMBER() OVER (ORDER BY bxi.avg_rating DESC, COALESCE(goal_counts.goals, 0) DESC, bxi.player_id ASC) as new_order
                FROM best_xi_jornada bxi
                LEFT JOIN LATERAL (
                    SELECT COUNT(*)::INTEGER as goals FROM goal_events ge
                    INNER JOIN matches m ON ge.match_uuid = m.match_uuid
                    WHERE ge.player_id = bxi.player_id AND ge.event_type != 'own_goal'
                      AND m.competition_id = p_competition_id AND m.season = p_season AND m.round_id = p_jornada
                ) goal_counts ON true
                WHERE bxi.competition_id = p_competition_id AND bxi.season = p_season AND bxi.jornada = p_jornada
                  AND bxi.position = v_pos_classified
            ) sub
            WHERE best_xi_jornada.player_id = sub.player_id AND best_xi_jornada.competition_id = p_competition_id
              AND best_xi_jornada.season = p_season AND best_xi_jornada.jornada = p_jornada;
        END IF;
    END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION calculate_best_xi_all_jornadas(p_competition_id integer)
 RETURNS void LANGUAGE plpgsql AS $function$
DECLARE
    v_season TEXT; v_jornada INTEGER;
BEGIN
    SELECT season INTO v_season FROM competitions WHERE id = p_competition_id;
    IF v_season IS NULL THEN RAISE EXCEPTION 'No se encontró la competición %', p_competition_id; END IF;
    FOR v_jornada IN
        SELECT DISTINCT round_id FROM matches
        WHERE competition_id = p_competition_id AND home_goals IS NOT NULL AND away_goals IS NOT NULL
          AND (resolved_administratively IS NULL OR resolved_administratively = false)
        ORDER BY round_id
    LOOP
        PERFORM calculate_best_xi_jornada(p_competition_id, v_season, v_jornada);
    END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION calculate_mvp_all_jornadas(p_competition_id integer)
 RETURNS void LANGUAGE plpgsql AS $function$
DECLARE v_jornada INTEGER;
BEGIN
    FOR v_jornada IN
        SELECT DISTINCT round_id FROM matches
        WHERE competition_id = p_competition_id AND round_id IS NOT NULL
          AND (resolved_administratively IS NULL OR resolved_administratively = false)
        ORDER BY round_id
    LOOP
        PERFORM calculate_mvp_jornada(p_competition_id, v_jornada);
    END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION calculate_period_awards(p_competition_id integer, p_season text, p_period_number integer, p_start_jornada integer, p_end_jornada integer)
 RETURNS integer LANGUAGE plpgsql AS $function$
DECLARE
    v_best_player_id INTEGER; v_best_player_avg_rating NUMERIC(4, 2); v_best_player_matches_count INTEGER;
    v_best_coach_team_id INTEGER; v_best_coach_avg_mvp_score NUMERIC(10, 2);
    v_total_matches INTEGER; v_played_matches INTEGER; v_is_period_complete BOOLEAN;
BEGIN
    SELECT COUNT(*) INTO v_total_matches FROM matches
    WHERE competition_id = p_competition_id AND season = p_season AND round_id >= p_start_jornada AND round_id <= p_end_jornada;

    SELECT COUNT(*) INTO v_played_matches FROM matches
    WHERE competition_id = p_competition_id AND season = p_season AND round_id >= p_start_jornada AND round_id <= p_end_jornada AND is_played = true;

    v_is_period_complete := (v_total_matches > 0 AND v_played_matches = v_total_matches);
    IF v_total_matches = 0 THEN RETURN 0; END IF;

    IF NOT v_is_period_complete THEN
        INSERT INTO monthly_awards (competition_id, season, period_number, start_jornada, end_jornada, player_id, player_avg_rating, player_matches_count, coach_league_team_id, coach_avg_mvp_score, is_period_complete)
        VALUES (p_competition_id, p_season, p_period_number, p_start_jornada, p_end_jornada, NULL, NULL, NULL, NULL, NULL, false)
        ON CONFLICT (competition_id, season, period_number) DO UPDATE SET is_period_complete = false, updated_at = NOW();
        RETURN 0;
    END IF;

    WITH period_mean AS (
        SELECT AVG(mpr.rating)::NUMERIC AS mean_rating FROM match_player_ratings mpr
        INNER JOIN matches m ON mpr.match_uuid = m.match_uuid
        WHERE m.competition_id = p_competition_id AND m.season = p_season
          AND m.round_id >= p_start_jornada AND m.round_id <= p_end_jornada
          AND mpr.rating IS NOT NULL AND m.home_goals IS NOT NULL AND m.away_goals IS NOT NULL
          AND (m.resolved_administratively IS NULL OR m.resolved_administratively = false)
    ),
    player_agg AS (
        SELECT prj.player_id, SUM(prj.total_rating_sum) AS total_sum, SUM(prj.matches_count)::INTEGER AS total_matches
        FROM player_ratings_jornada prj
        WHERE prj.competition_id = p_competition_id AND prj.season = p_season
          AND prj.jornada >= p_start_jornada AND prj.jornada <= p_end_jornada AND prj.avg_rating IS NOT NULL
        GROUP BY prj.player_id HAVING SUM(prj.matches_count) >= 3
    )
    SELECT pa.player_id,
        ROUND(((4.0 * COALESCE(pm.mean_rating, 0) + pa.total_matches * (pa.total_sum / NULLIF(pa.total_matches, 0))) / (4 + pa.total_matches))::NUMERIC, 2),
        pa.total_matches
    INTO v_best_player_id, v_best_player_avg_rating, v_best_player_matches_count
    FROM player_agg pa CROSS JOIN period_mean pm
    ORDER BY 2 DESC, pa.total_matches DESC, pa.player_id ASC LIMIT 1;

    SELECT mj.league_team_id, AVG(mj.mvp_score)::NUMERIC(10, 2)
    INTO v_best_coach_team_id, v_best_coach_avg_mvp_score
    FROM mvp_jornada mj
    WHERE mj.competition_id = p_competition_id AND mj.season = p_season
      AND mj.jornada >= p_start_jornada AND mj.jornada <= p_end_jornada AND mj.mvp_score IS NOT NULL
    GROUP BY mj.league_team_id ORDER BY AVG(mj.mvp_score) DESC, COUNT(*) DESC, mj.league_team_id ASC LIMIT 1;

    INSERT INTO monthly_awards (competition_id, season, period_number, start_jornada, end_jornada, player_id, player_avg_rating, player_matches_count, coach_league_team_id, coach_avg_mvp_score, is_period_complete)
    VALUES (p_competition_id, p_season, p_period_number, p_start_jornada, p_end_jornada, v_best_player_id, v_best_player_avg_rating, v_best_player_matches_count, v_best_coach_team_id, v_best_coach_avg_mvp_score, true)
    ON CONFLICT (competition_id, season, period_number)
    DO UPDATE SET start_jornada = EXCLUDED.start_jornada, end_jornada = EXCLUDED.end_jornada, player_id = EXCLUDED.player_id,
                  player_avg_rating = EXCLUDED.player_avg_rating, player_matches_count = EXCLUDED.player_matches_count,
                  coach_league_team_id = EXCLUDED.coach_league_team_id, coach_avg_mvp_score = EXCLUDED.coach_avg_mvp_score,
                  is_period_complete = true, updated_at = NOW();

    RETURN v_played_matches;
END;
$function$;

CREATE OR REPLACE FUNCTION calculate_monthly_awards(p_competition_id integer, p_season text)
 RETURNS void LANGUAGE plpgsql AS $function$
DECLARE
    v_competition_type TEXT; v_max_jornada INTEGER; v_period_number INTEGER;
    v_start_jornada INTEGER; v_end_jornada INTEGER; v_jornada_count INTEGER;
BEGIN
    SELECT competition_type INTO v_competition_type FROM competitions WHERE id = p_competition_id;
    IF v_competition_type != 'league' THEN RETURN; END IF;

    DELETE FROM monthly_awards WHERE competition_id = p_competition_id AND season = p_season;

    SELECT MAX(round_id) INTO v_max_jornada FROM matches
    WHERE competition_id = p_competition_id AND season = p_season AND round_id IS NOT NULL;
    IF v_max_jornada IS NULL THEN RETURN; END IF;

    v_period_number := 1; v_start_jornada := 1;
    WHILE v_start_jornada <= v_max_jornada LOOP
        v_end_jornada := v_start_jornada + 3;
        SELECT COUNT(DISTINCT round_id) INTO v_jornada_count FROM matches
        WHERE competition_id = p_competition_id AND season = p_season AND round_id BETWEEN v_start_jornada AND v_end_jornada;
        IF v_jornada_count > 0 THEN
            PERFORM calculate_period_awards(p_competition_id, p_season, v_period_number, v_start_jornada, v_end_jornada);
        END IF;
        v_period_number := v_period_number + 1;
        v_start_jornada := v_start_jornada + 4;
    END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION trigger_recalculate_best_xi_jornada() RETURNS trigger LANGUAGE plpgsql AS $function$
DECLARE
    v_competition_id INTEGER; v_season TEXT; v_jornada INTEGER;
    v_match_uuid INTEGER; v_resolved BOOLEAN; v_new_match_uuid INTEGER; v_old_match_uuid INTEGER;
BEGIN
    v_new_match_uuid := CASE WHEN TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN NEW.match_uuid ELSE NULL END;
    v_old_match_uuid := CASE WHEN TG_OP = 'UPDATE' OR TG_OP = 'DELETE' THEN OLD.match_uuid ELSE NULL END;
    v_match_uuid := COALESCE(v_new_match_uuid, v_old_match_uuid);
    IF v_match_uuid IS NULL THEN RETURN COALESCE(NEW, OLD); END IF;

    SELECT m.competition_id, m.season, m.round_id, COALESCE(m.resolved_administratively, false)
    INTO v_competition_id, v_season, v_jornada, v_resolved
    FROM matches m WHERE m.match_uuid = v_match_uuid LIMIT 1;

    IF v_competition_id IS NOT NULL AND v_season IS NOT NULL AND v_jornada IS NOT NULL THEN
        IF NOT v_resolved THEN
            BEGIN PERFORM calculate_best_xi_jornada(v_competition_id, v_season, v_jornada);
            EXCEPTION WHEN OTHERS THEN RAISE WARNING 'Error recalculando Best XI para jornada %: %', v_jornada, SQLERRM; END;
            BEGIN PERFORM calculate_best_player_jornada(v_competition_id, v_season, v_jornada);
            EXCEPTION WHEN OTHERS THEN RAISE WARNING 'Error recalculando Best Player para jornada %: %', v_jornada, SQLERRM; END;
        END IF;
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$function$;

CREATE OR REPLACE FUNCTION trigger_recalculate_best_xi_on_match_update() RETURNS trigger LANGUAGE plpgsql AS $function$
DECLARE
    v_competition_id INTEGER; v_season TEXT; v_jornada INTEGER; v_resolved BOOLEAN;
    v_was_played BOOLEAN; v_is_played BOOLEAN;
BEGIN
    v_was_played := (OLD.home_goals IS NOT NULL AND OLD.away_goals IS NOT NULL);
    v_is_played := (NEW.home_goals IS NOT NULL AND NEW.away_goals IS NOT NULL);
    IF (v_was_played <> v_is_played) OR (COALESCE(OLD.resolved_administratively, false) <> COALESCE(NEW.resolved_administratively, false)) THEN
        v_competition_id := NEW.competition_id; v_season := NEW.season; v_jornada := NEW.round_id;
        v_resolved := COALESCE(NEW.resolved_administratively, false);
        IF v_competition_id IS NOT NULL AND v_season IS NOT NULL AND v_jornada IS NOT NULL THEN
            IF NOT v_resolved AND v_is_played THEN
                BEGIN PERFORM calculate_best_xi_jornada(v_competition_id, v_season, v_jornada);
                EXCEPTION WHEN OTHERS THEN RAISE WARNING 'Error recalculando Best XI para jornada %: %', v_jornada, SQLERRM; END;
                BEGIN PERFORM calculate_best_player_jornada(v_competition_id, v_season, v_jornada);
                EXCEPTION WHEN OTHERS THEN RAISE WARNING 'Error recalculando Best Player para jornada %: %', v_jornada, SQLERRM; END;
            END IF;
        END IF;
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION trigger_recalculate_mvp_jornada() RETURNS trigger LANGUAGE plpgsql AS $function$
DECLARE
    v_competition_id INTEGER; v_jornada INTEGER; v_match_uuid INTEGER;
    v_new_match_uuid INTEGER; v_old_match_uuid INTEGER; v_resolved BOOLEAN;
BEGIN
    v_new_match_uuid := CASE WHEN TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN NEW.match_uuid ELSE NULL END;
    v_old_match_uuid := CASE WHEN TG_OP = 'UPDATE' OR TG_OP = 'DELETE' THEN OLD.match_uuid ELSE NULL END;
    v_match_uuid := COALESCE(v_new_match_uuid, v_old_match_uuid);

    SELECT m.competition_id, m.round_id INTO v_competition_id, v_jornada
    FROM matches m WHERE m.match_uuid = v_match_uuid LIMIT 1;

    IF v_competition_id IS NOT NULL AND v_jornada IS NOT NULL THEN
        SELECT COALESCE(resolved_administratively, false) INTO v_resolved FROM matches WHERE match_uuid = v_match_uuid;
        IF NOT v_resolved THEN
            BEGIN PERFORM calculate_mvp_jornada(v_competition_id, v_jornada);
            EXCEPTION WHEN OTHERS THEN RAISE WARNING 'Error recalculando MVP para jornada %: %', v_jornada, SQLERRM; END;
        END IF;
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$function$;

CREATE TRIGGER trigger_match_player_ratings_best_xi AFTER INSERT OR UPDATE ON match_player_ratings
  FOR EACH ROW WHEN (NEW.rating IS NOT NULL) EXECUTE FUNCTION trigger_recalculate_best_xi_jornada();
CREATE TRIGGER trigger_matches_best_xi AFTER UPDATE OF home_goals, away_goals, resolved_administratively ON matches
  FOR EACH ROW WHEN (NEW.home_goals IS NOT NULL AND NEW.away_goals IS NOT NULL) EXECUTE FUNCTION trigger_recalculate_best_xi_on_match_update();
CREATE TRIGGER trigger_match_team_stats_mvp AFTER INSERT OR UPDATE ON match_team_stats
  FOR EACH ROW WHEN (NEW.possession IS NOT NULL OR NEW.fouls IS NOT NULL OR NEW.tackles IS NOT NULL OR NEW.passes IS NOT NULL OR NEW.shots IS NOT NULL OR NEW.goals IS NOT NULL)
  EXECUTE FUNCTION trigger_recalculate_mvp_jornada();

CREATE OR REPLACE FUNCTION get_best_player_jornada(p_competition_id integer, p_season text, p_jornada integer)
 RETURNS TABLE(player_id integer, player_name text, player_position text, avg_rating numeric, matches_count bigint, league_team_id integer, team_nickname text, club_crest text)
 LANGUAGE plpgsql AS $function$
BEGIN
    RETURN QUERY
    SELECT prj.player_id, prj.player_name, prj.position AS player_position, prj.avg_rating,
           prj.matches_count::BIGINT, prj.league_team_id, prj.team_nickname, prj.club_crest
    FROM player_ratings_jornada prj
    LEFT JOIN LATERAL (
        SELECT COUNT(*)::INTEGER AS goals FROM goal_events ge
        INNER JOIN matches m ON ge.match_uuid = m.match_uuid
        WHERE ge.player_id = prj.player_id AND ge.event_type != 'own_goal'
          AND m.competition_id = p_competition_id AND m.season = p_season AND m.round_id = p_jornada
    ) goal_counts ON true
    WHERE prj.competition_id = p_competition_id AND prj.season = p_season AND prj.jornada = p_jornada
    ORDER BY prj.avg_rating DESC, COALESCE(goal_counts.goals, 0) DESC, prj.player_id ASC LIMIT 1;
END;
$function$;

CREATE OR REPLACE FUNCTION get_best_xi_jornada(p_competition_id integer, p_season text, p_jornada integer)
 RETURNS TABLE(player_id integer, player_name text, player_position character varying, avg_rating numeric, matches_count bigint, league_team_id integer, team_nickname text, club_crest text, position_order integer, mvp_team_id integer, mvp_team_name text, mvp_team_display_name text)
 LANGUAGE plpgsql AS $function$
BEGIN
    RETURN QUERY
    SELECT bxi.player_id, COALESCE(p.name, 'Unknown')::TEXT AS player_name, bxi.position AS player_position,
           bxi.avg_rating, bxi.matches_count::BIGINT, pra.league_team_id AS player_league_team_id,
           pra.team_nickname, pra.club_crest, bxi.position_order,
           mvp.league_team_id AS mvp_team_id, lt_mvp.nickname AS mvp_team_name, lt_mvp.display_name AS mvp_team_display_name
    FROM best_xi_jornada bxi
    LEFT JOIN players p ON bxi.player_id = p.id
    LEFT JOIN player_ratings_jornada pra ON pra.player_id = bxi.player_id AND pra.competition_id = bxi.competition_id
      AND pra.season = bxi.season AND pra.jornada = bxi.jornada
    LEFT JOIN (
        SELECT mj.league_team_id FROM mvp_jornada mj
        WHERE mj.competition_id = p_competition_id AND mj.season = p_season AND mj.jornada = p_jornada
        ORDER BY mj.mvp_score DESC LIMIT 1
    ) mvp ON true
    LEFT JOIN league_teams lt_mvp ON mvp.league_team_id = lt_mvp.id
    WHERE bxi.competition_id = p_competition_id AND bxi.season = p_season AND bxi.jornada = p_jornada
    ORDER BY CASE bxi.position WHEN 'GK' THEN 1 WHEN 'DEF' THEN 2 WHEN 'MID' THEN 3 WHEN 'FWD' THEN 4 END, bxi.position_order;
END;
$function$;

CREATE OR REPLACE FUNCTION get_monthly_awards(p_competition_id integer, p_season text)
 RETURNS TABLE(id bigint, period_number integer, start_jornada integer, end_jornada integer, player_id integer, player_name text, player_avg_rating numeric, player_matches_count integer, coach_league_team_id integer, coach_team_nickname text, coach_team_display_name text, coach_avg_mvp_score numeric, is_period_complete boolean)
 LANGUAGE plpgsql AS $function$
BEGIN
    RETURN QUERY
    SELECT ma.id, ma.period_number, ma.start_jornada, ma.end_jornada, ma.player_id, p.name::TEXT AS player_name,
           ma.player_avg_rating, ma.player_matches_count, ma.coach_league_team_id,
           lt.nickname::TEXT AS coach_team_nickname, lt.display_name::TEXT AS coach_team_display_name,
           ma.coach_avg_mvp_score, ma.is_period_complete
    FROM monthly_awards ma
    LEFT JOIN players p ON ma.player_id = p.id
    LEFT JOIN league_teams lt ON ma.coach_league_team_id = lt.id
    WHERE ma.competition_id = p_competition_id AND ma.season = p_season AND ma.is_period_complete = true
    ORDER BY ma.period_number ASC;
END;
$function$;
