-- Formaciones automáticas (introspectado 2026-07-07). Se recalculan solas
-- cuando entran ratings de jugador, igual que el Best XI/MVP.

CREATE TYPE player_role AS ENUM ('pilar', 'rotacion', 'joven_promesa', 'descarte', 'recuperacion');

CREATE TABLE formations (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id        bigint NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  season         text NOT NULL,
  system         text NOT NULL,
  created_at     timestamptz DEFAULT now(),
  updated_at     timestamptz DEFAULT now(),
  competition_id integer REFERENCES competitions(id),
  league_team_id integer REFERENCES league_teams(id),
  UNIQUE (league_team_id, competition_id)
);

CREATE TABLE formation_slots (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  formation_id bigint NOT NULL REFERENCES formations(id) ON DELETE CASCADE,
  slot_index   smallint NOT NULL,
  player_id    bigint REFERENCES players(id),
  created_at   timestamptz DEFAULT now(),
  updated_at   timestamptz DEFAULT now(),
  UNIQUE (formation_id, slot_index)
);

CREATE TABLE team_player_roles (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id    bigint NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  player_id  bigint NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  season     text NOT NULL,
  role       player_role NOT NULL,
  note       text CHECK (note IS NULL OR length(note) <= 200),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (club_id, player_id, season)
);

CREATE OR REPLACE FUNCTION map_formation_to_system(p_def_count integer, p_mid_count integer, p_fwd_count integer)
 RETURNS text LANGUAGE plpgsql IMMUTABLE AS $function$
BEGIN
    IF p_def_count = 4 AND p_mid_count = 4 AND p_fwd_count = 2 THEN RETURN '4-4-2';
    ELSIF p_def_count = 4 AND p_mid_count = 3 AND p_fwd_count = 3 THEN RETURN '4-3-3';
    ELSIF p_def_count = 4 AND p_mid_count = 5 AND p_fwd_count = 1 THEN RETURN '4-5-1';
    ELSIF p_def_count = 3 AND p_mid_count = 5 AND p_fwd_count = 2 THEN RETURN '3-5-2';
    ELSE RETURN p_def_count || '-' || p_mid_count || '-' || p_fwd_count;
    END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION calculate_club_formation(p_league_team_id integer, p_competition_id integer)
 RETURNS jsonb LANGUAGE plpgsql AS $function$
DECLARE
    v_season TEXT; v_club_id INTEGER; v_gk_player_id INTEGER; v_gk_player_name TEXT;
    v_def_count INTEGER; v_mid_count INTEGER; v_fwd_count INTEGER;
    v_best_def_count INTEGER := 4; v_best_mid_count INTEGER := 3; v_best_fwd_count INTEGER := 3;
    v_best_sum NUMERIC := 0; v_current_sum NUMERIC;
    v_max_def INTEGER; v_max_mid INTEGER; v_max_fwd INTEGER;
    v_min_def INTEGER; v_min_mid INTEGER; v_min_fwd INTEGER;
    v_def_available INTEGER; v_mid_available INTEGER; v_fwd_available INTEGER;
    v_formation_id BIGINT; v_system TEXT; v_slot_index INTEGER; v_result JSONB; v_player_id INTEGER;
BEGIN
    SELECT season INTO v_season FROM competitions WHERE id = p_competition_id;
    IF v_season IS NULL THEN RAISE EXCEPTION 'No se encontró la competición %', p_competition_id; END IF;

    SELECT club_id INTO v_club_id FROM league_teams WHERE id = p_league_team_id AND competition_id = p_competition_id;
    IF v_club_id IS NULL THEN RAISE EXCEPTION 'No se encontró el club para el league_team_id % en la competición %', p_league_team_id, p_competition_id; END IF;

    SELECT player_id, player_name INTO v_gk_player_id, v_gk_player_name
    FROM player_ratings_avg
    WHERE league_team_id = p_league_team_id AND competition_id = p_competition_id AND classify_position(position) = 'GK'
    ORDER BY bayesian_rating DESC, matches_count DESC LIMIT 1;
    IF v_gk_player_id IS NULL THEN RAISE EXCEPTION 'No se encontró portero para el equipo %', p_league_team_id; END IF;

    SELECT COUNT(*) INTO v_def_available FROM player_ratings_avg WHERE league_team_id = p_league_team_id AND competition_id = p_competition_id AND classify_position(position) = 'DEF';
    SELECT COUNT(*) INTO v_mid_available FROM player_ratings_avg WHERE league_team_id = p_league_team_id AND competition_id = p_competition_id AND classify_position(position) = 'MID';
    SELECT COUNT(*) INTO v_fwd_available FROM player_ratings_avg WHERE league_team_id = p_league_team_id AND competition_id = p_competition_id AND classify_position(position) = 'FWD';

    v_max_def := LEAST(COALESCE(v_def_available, 0), 5);
    v_max_mid := LEAST(COALESCE(v_mid_available, 0), 5);
    v_max_fwd := LEAST(COALESCE(v_fwd_available, 0), 3);
    v_min_def := GREATEST(LEAST(v_max_def, 3), 0);
    v_min_mid := GREATEST(LEAST(v_max_mid, 3), 0);
    v_min_fwd := GREATEST(LEAST(v_max_fwd, 1), 0);

    FOR v_def_count IN v_min_def..v_max_def LOOP
        FOR v_mid_count IN v_min_mid..v_max_mid LOOP
            FOR v_fwd_count IN v_min_fwd..v_max_fwd LOOP
                IF (v_def_count + v_mid_count + v_fwd_count) = 10 THEN
                    SELECT COALESCE(
                        (SELECT SUM(bayesian_rating) FROM (
                            SELECT bayesian_rating, ROW_NUMBER() OVER (ORDER BY bayesian_rating DESC, matches_count DESC) AS rn
                            FROM player_ratings_avg WHERE league_team_id = p_league_team_id AND competition_id = p_competition_id AND classify_position(position) = 'DEF'
                        ) def_ratings WHERE rn <= v_def_count)
                        +
                        (SELECT SUM(bayesian_rating) FROM (
                            SELECT bayesian_rating, ROW_NUMBER() OVER (ORDER BY bayesian_rating DESC, matches_count DESC) AS rn
                            FROM player_ratings_avg WHERE league_team_id = p_league_team_id AND competition_id = p_competition_id AND classify_position(position) = 'MID'
                        ) mid_ratings WHERE rn <= v_mid_count)
                        +
                        (SELECT SUM(bayesian_rating) FROM (
                            SELECT bayesian_rating, ROW_NUMBER() OVER (ORDER BY bayesian_rating DESC, matches_count DESC) AS rn
                            FROM player_ratings_avg WHERE league_team_id = p_league_team_id AND competition_id = p_competition_id AND classify_position(position) = 'FWD'
                        ) fwd_ratings WHERE rn <= v_fwd_count), 0
                    ) INTO v_current_sum;

                    IF v_current_sum > v_best_sum THEN
                        v_best_sum := v_current_sum;
                        v_best_def_count := v_def_count; v_best_mid_count := v_mid_count; v_best_fwd_count := v_fwd_count;
                    END IF;
                END IF;
            END LOOP;
        END LOOP;
    END LOOP;

    IF v_best_sum = 0 THEN
        v_best_def_count := v_max_def; v_best_mid_count := v_max_mid; v_best_fwd_count := v_max_fwd;
        WHILE (v_best_def_count + v_best_mid_count + v_best_fwd_count) < 10
              AND (v_best_def_count < v_max_def OR v_best_mid_count < v_max_mid OR v_best_fwd_count < v_max_fwd) LOOP
            IF v_best_def_count < v_max_def AND v_def_available > v_best_def_count THEN v_best_def_count := v_best_def_count + 1;
            ELSIF v_best_mid_count < v_max_mid AND v_mid_available > v_best_mid_count THEN v_best_mid_count := v_best_mid_count + 1;
            ELSIF v_best_fwd_count < v_max_fwd AND v_fwd_available > v_best_fwd_count THEN v_best_fwd_count := v_best_fwd_count + 1;
            ELSE EXIT;
            END IF;
        END LOOP;
        WHILE (v_best_def_count + v_best_mid_count + v_best_fwd_count) > 10 LOOP
            IF v_best_fwd_count > 1 THEN v_best_fwd_count := v_best_fwd_count - 1;
            ELSIF v_best_mid_count > 3 THEN v_best_mid_count := v_best_mid_count - 1;
            ELSIF v_best_def_count > 3 THEN v_best_def_count := v_best_def_count - 1;
            ELSE EXIT;
            END IF;
        END LOOP;
    END IF;

    v_system := map_formation_to_system(v_best_def_count, v_best_mid_count, v_best_fwd_count);

    INSERT INTO formations (club_id, league_team_id, season, system, competition_id)
    VALUES (v_club_id, p_league_team_id, v_season, v_system, p_competition_id)
    ON CONFLICT (league_team_id, competition_id)
    DO UPDATE SET system = EXCLUDED.system, season = EXCLUDED.season, club_id = EXCLUDED.club_id
    RETURNING id INTO v_formation_id;

    DELETE FROM formation_slots WHERE formation_id = v_formation_id;
    INSERT INTO formation_slots (formation_id, slot_index, player_id) VALUES (v_formation_id, 0, v_gk_player_id);
    v_slot_index := 1;

    FOR v_player_id IN
        SELECT player_id FROM player_ratings_avg
        WHERE league_team_id = p_league_team_id AND competition_id = p_competition_id AND classify_position(position) = 'DEF'
        ORDER BY bayesian_rating DESC, matches_count DESC LIMIT v_best_def_count
    LOOP
        INSERT INTO formation_slots (formation_id, slot_index, player_id) VALUES (v_formation_id, v_slot_index, v_player_id);
        v_slot_index := v_slot_index + 1;
    END LOOP;

    FOR v_player_id IN
        SELECT player_id FROM player_ratings_avg
        WHERE league_team_id = p_league_team_id AND competition_id = p_competition_id AND classify_position(position) = 'MID'
        ORDER BY bayesian_rating DESC, matches_count DESC LIMIT v_best_mid_count
    LOOP
        INSERT INTO formation_slots (formation_id, slot_index, player_id) VALUES (v_formation_id, v_slot_index, v_player_id);
        v_slot_index := v_slot_index + 1;
    END LOOP;

    FOR v_player_id IN
        SELECT player_id FROM player_ratings_avg
        WHERE league_team_id = p_league_team_id AND competition_id = p_competition_id AND classify_position(position) = 'FWD'
        ORDER BY bayesian_rating DESC, matches_count DESC LIMIT v_best_fwd_count
    LOOP
        INSERT INTO formation_slots (formation_id, slot_index, player_id) VALUES (v_formation_id, v_slot_index, v_player_id);
        v_slot_index := v_slot_index + 1;
    END LOOP;

    SELECT jsonb_build_object(
        'formation_id', v_formation_id, 'system', v_system,
        'slots', (SELECT jsonb_agg(jsonb_build_object('slot_index', slot_index, 'player_id', player_id) ORDER BY slot_index)
                  FROM formation_slots WHERE formation_id = v_formation_id)
    ) INTO v_result;

    RETURN v_result;
END;
$function$;

CREATE OR REPLACE FUNCTION get_club_formation(p_league_team_id integer, p_competition_id integer)
 RETURNS jsonb LANGUAGE plpgsql AS $function$
DECLARE v_result JSONB;
BEGIN
    v_result := calculate_club_formation(p_league_team_id, p_competition_id);
    RETURN v_result;
END;
$function$;

CREATE OR REPLACE FUNCTION trigger_recalculate_club_formation() RETURNS trigger LANGUAGE plpgsql AS $function$
DECLARE
    v_league_team_id INTEGER; v_competition_id INTEGER;
    v_new_league_team_id INTEGER; v_old_league_team_id INTEGER;
    v_new_competition_id INTEGER; v_old_competition_id INTEGER;
BEGIN
    v_new_league_team_id := CASE WHEN TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN NEW.league_team_id ELSE NULL END;
    v_old_league_team_id := CASE WHEN TG_OP = 'UPDATE' OR TG_OP = 'DELETE' THEN OLD.league_team_id ELSE NULL END;
    v_new_competition_id := CASE WHEN TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN NEW.competition_id ELSE NULL END;
    v_old_competition_id := CASE WHEN TG_OP = 'UPDATE' OR TG_OP = 'DELETE' THEN OLD.competition_id ELSE NULL END;

    v_league_team_id := COALESCE(v_new_league_team_id, v_old_league_team_id);
    v_competition_id := COALESCE(v_new_competition_id, v_old_competition_id);

    IF v_league_team_id IS NOT NULL AND v_competition_id IS NOT NULL THEN
        IF (TG_OP = 'INSERT' OR TG_OP = 'UPDATE') AND NEW.rating IS NOT NULL THEN
            BEGIN PERFORM calculate_club_formation(v_league_team_id, v_competition_id);
            EXCEPTION WHEN OTHERS THEN RAISE WARNING 'Error recalculando formación para league_team_id %: %', v_league_team_id, SQLERRM; END;
        END IF;
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$function$;

CREATE TRIGGER trigger_match_player_ratings_club_formation AFTER INSERT OR UPDATE ON match_player_ratings
  FOR EACH ROW WHEN (NEW.rating IS NOT NULL) EXECUTE FUNCTION trigger_recalculate_club_formation();
