// Importa el catálogo real de continents/leagues/clubs/players/
// player_club_memberships desde el Supabase de producción de `lliga` (la
// app online, solo lectura vía anonKey pública) hacia la instancia PGlite
// local de liga-offline. Se conserva el id original de cada fila (los
// rangos de producción llegan a los 10 millones, muy por encima de
// cualquier id sintético que uses en seed-dev.mjs) para que
// player_club_memberships no necesite remapear FKs.
//
// Uso: node scripts/import-catalog.mjs
// Requiere que server.mjs esté corriendo (para el socket local 55432).

if (typeof globalThis.WebSocket === 'undefined') {
  const { WebSocket } = await import('ws');
  globalThis.WebSocket = WebSocket;
}

import { createClient } from '@supabase/supabase-js';
import pg from 'pg';

const PROD = {
  url: 'https://jdbjgrkvwawdibntngpk.supabase.co',
  anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkYmpncmt2d2F3ZGlibnRuZ3BrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwMTQ4NTQsImV4cCI6MjA3OTU5MDg1NH0.t8KkjGmcCwriKfcG8pzZfCwqgddyG2jmYFxuAHH4NfA',
};

const sbProd = createClient(PROD.url, PROD.anonKey, { auth: { autoRefreshToken: false, persistSession: false } });

const client = new pg.Client({ host: '127.0.0.1', port: 55432, database: 'postgres', user: 'authenticator', password: 'localdev' });
await client.connect();

// Trae todas las filas de una tabla, paginando de 1000 en 1000 (límite de PostgREST).
async function fetchAll(table, columns) {
  const rows = [];
  const pageSize = 1000;
  for (let from = 0; ; from += pageSize) {
    const { data, error } = await sbProd.from(table).select(columns).range(from, from + pageSize - 1);
    if (error) throw new Error(`Error leyendo ${table}: ${error.message}`);
    rows.push(...data);
    if (data.length < pageSize) break;
  }
  return rows;
}

async function insertRows(table, columns, rows) {
  if (!rows.length) return 0;
  for (const row of rows) {
    const values = columns.map((c) => row[c] ?? null);
    const placeholders = columns.map((_, i) => `$${i + 1}`).join(', ');
    await client.query(
      `INSERT INTO ${table} (${columns.join(', ')}) VALUES (${placeholders}) ON CONFLICT (id) DO NOTHING`,
      values
    );
  }
  return rows.length;
}

console.log('[import-catalog] Leyendo de producción...');

const continents = await fetchAll('continents', 'id, code, name, created_at');
const leagues = await fetchAll('leagues', 'id, name, country, continent_id, short_name, created_at');
const clubs = await fetchAll('clubs', 'id, name, short_name, tla, crest_url, country, venue, created_at, address, website, founded, club_colors, league_id, continent_id, pes_name, city');
const players = await fetchAll('players', 'id, name, position, date_of_birth, nationality, created_at, efootball_id, efootball_overall, efootball_potential, efootball_cost_gp');
const memberships = await fetchAll('player_club_memberships', 'id, player_id, club_id, season, from_round, to_round, is_current, created_at');

console.log(`[import-catalog] continents=${continents.length} leagues=${leagues.length} clubs=${clubs.length} players=${players.length} memberships=${memberships.length}`);

const nContinents = await insertRows('continents', ['id', 'code', 'name', 'created_at'], continents);
const nLeagues = await insertRows('leagues', ['id', 'name', 'country', 'continent_id', 'short_name', 'created_at'], leagues);
const nClubs = await insertRows('clubs', ['id', 'name', 'short_name', 'tla', 'crest_url', 'country', 'venue', 'created_at', 'address', 'website', 'founded', 'club_colors', 'league_id', 'continent_id', 'pes_name', 'city'], clubs);
const nPlayers = await insertRows('players', ['id', 'name', 'position', 'date_of_birth', 'nationality', 'created_at', 'efootball_id', 'efootball_overall', 'efootball_potential', 'efootball_cost_gp'], players);
const nMemberships = await insertRows('player_club_memberships', ['id', 'player_id', 'club_id', 'season', 'from_round', 'to_round', 'is_current', 'created_at'], memberships);

// continents/leagues tienen id GENERATED BY DEFAULT AS IDENTITY: al insertar
// ids explícitos hay que avanzar la secuencia para que el próximo INSERT sin
// id (p.ej. desde la app) no choque con uno ya importado.
await client.query(`SELECT setval('continents_id_seq', COALESCE((SELECT MAX(id) FROM continents), 1), true);`);
await client.query(`SELECT setval('leagues_id_seq', COALESCE((SELECT MAX(id) FROM leagues), 1), true);`);

console.log(`[import-catalog] Insertados: continents=${nContinents} leagues=${nLeagues} clubs=${nClubs} players=${nPlayers} memberships=${nMemberships}`);
console.log('[import-catalog] Listo.');

await client.end();
